[es esm]	//Spanish

D64EP1 = "Doom 64";
D64EP2 = "Doom 64 (Omitir intro)";
D64REC = "El Juicio Final";
D64EP3 = "Partida a muerte (Zandronum)";
D64EP4 = "Centro de pruebas";

D64QUIT = "¿Salir de Brutal Doom 64?";

////////////////////////////////////////////////////////////////////////////////
// Level names

TITLEMAP = "Menú principal";
D64TM = "Centro de pruebas";

D6400 = "Punto de desembarco";
D6401 = "Zona de preparación";
D6402 = "El terraformador";
D6403 = "Ingeniería principal";
D6404 = "Zona de contención";
D6405 = "Centro técnico";
D6406 = "Cuadrante Alfa";
D6407 = "Laboratorio de investigación";
D6408 = "Puesto de avanzada final";
D6409 = "Aún más simple";
D6410 = "El sangrado";
D6411 = "Núcleo del terror";
D6412 = "Altar del dolor";
D6413 = "Ciudadela oscura";
D6414 = "Ojo de la tormenta";
D6415 = "Entradas oscuras";
D6416 = "Fortaleza de sangre";
D6417 = "Cuidado por dónde pisas";
D6418 = "Miedo engendrado";
D6419 = "La espiral";
D6420 = "Colapso";
D6421 = "Trampas ocultas";
D6422 = "Ofrendas quemadas";
D6423 = "Templo profano";
D6424 = "Sin salida";
D6425 = "El gato y el ratón";
D6426 = "Extremo";
D6427 = "Zona de juegos";
D6428 = "La absolución final";
D6428A = "La absolución";
D6429 = "Puesto de avanzada Omega";
D6430 = "La guarida";
D6431 = "En el vacío";
D6432 = "Héctico";

ENDINGMA = "Fin";

D6407TC = "Planta de residuos (ABS)";
D6427TC = "Profundidad prohibida (ABS)";
D6428TC = "Sombras observando (ABS)";
D6434TC = "Crisis (ABS)";

REC01 = "Túneles (REC)";
REC02 = "Fosas peligrosas (REC)";
REC03 = "Cuadrante Delta (REC)";
REC04 = "Laboratorios de datos (REC)";
REC05 = "Núcleo del portal (REC)";
REC06 = "Ofrendas incineradas (REC)";
REC07 = "Cripta de sombras (REC)";
REC08 = "El círculo del caos (REC)";
REC09 = "Fuente del mal (REC)";

64DM1 = "Muerte simple (DM)";
64DM2 = "Muriendo solo (DM)";
64DM3 = "Altar de la agonía (DM)";
64DM4 = "La espiral descendente (DM)";
64DM5 = "Torre de la masacre (DM)";
64DM6 = "Colmena de tortura (DM)";
64DM7 = "Confrontación (DM)";

CD64 = "Club Doom 64";

AUTH_CRAN = "Rehecho por Craneo";
AUTH_RANDY_SAM = "Randy Estrella/Sam Villarreal";
AUTH_DANNY_SAM = "Danny Lewis/Sam Villarreal";
AUTH_TIM_LUTA = "Tim Heydelaar/Lutarez";
AUTH_SAM = "Sam Villarreal";
AUTH_TIM_DOOMER_SAM = "Tim Heydelaar/The Doomer/Sam Villarreal";
AUTH_SGTMARK = "Sgt Mark IV";
AUTH_TIM_SAM_MEL = "Tim Heydelaar/Sam Villarreal/Melfice";
AUTH_TIM_SAM = "Tim Heydelaar/Sam Villarreal";
AUTH_DANNY_DOOMER_SAM = "Danny Lewis/The Doomer/Sam Villarreal";
AUTH_RANDY_SAM_MEL = "Randy Estrella/Sam Villarreal/Melfice";
AUTH_TIM_ELBRY = "Sam Villarreal/Elbryan42";
AUTH_STYD = "Styd051";
AUTH_RANDY_DANNY_TIM_SAM = "Randy Estrella/Danny Lewis/Tim Heydelaar/Sam Villarreal";
AUTH_SEARLE = "Steven Searle";

////////////////////////////////////////////////////////////////////////////////
// Intermission screens

INTRO01_TXT = "¡Lo has logrado con éxito!\n"
"Mientras la puerta del ascensor se cierra tras de ti,\n"
"escuchas gemidos y gritos humanos y demoníacos,\n"
"mezclados con disparos y explosiones.\n"
"\n"
"Con el tiempo no escuchas nada más que silencio.\n"
"Tu equipo estaba totalmente despreparado para lo que\n"
"esperaba en el punto de desembarco.\n"
"\n"
"Tras un momento, te das cuenta de que estás solo.\n"
"\n"
"La sensación dentro de la base se siente mal, y ese olor,\n"
"recuerdas muy bien ese olor a muerte.\n"
"\n"
"Ya no hay marcha atrás.\n"
"Preparas tu arma y avanzas hacia la base.\n";

INTER01_TXT = "Las órdenes de la UAC eran eliminar la amenaza demoníaca.\n"
"\n"
"Has limpiado la base y llegado al portal.\n"
"Sin embargo, ¡parece que la UAC no ha aprendido nada\n"
"desde la primera invasión demoníaca!\n"
"\n"
"Consideras desactivar la secuencia de autodestrucción,\n"
"pero sabes que la UAC nunca aprenderá.\n"
"\n"
"¡Te vas a asegurar de que la UAC\n"
"no pueda volver a arruinarlo todo!\n"
"Deja que el portal y los experimentos de la UAC sean destruidos\n"
"junto con la base.\n"
"\n"
"Al cruzar el portal y disiparse la bruma,\n"
"la familiaridad de la situación te embarga.\n"
"Tu carcajada y tu grito sediento de sangre resuenan mientras\n"
"una vez más te encuentras\n"
"en medio de...\n";

INTER02_TXT = "El vasto silencio te recuerda\n"
	"a la morgue militar.\n"
	"\n"
	"Sabías que la instalación\n"
	"tenía un nivel clasificado.\n"
	"\n"
	"La U.A.C. tenía una buena razón\n"
	"para ocultar este lugar.\n"
	"\n"
	"Te preguntas qué\n"
	"podría ser...";

INTER03_TXT = "Sonríes.\n"
"¿En qué extraño lugar\n"
"has tropezado?\n"
"\n"
"Los demonios no esperaban\n"
"que sobrevivieras hasta aquí.\n"
"Sientes su presencia demoníaca\n"
"esperándote...\n"
"\n"
"¡Haz que se traguen sus propias entrañas!\n";

INTER04_TXT = "Al dar el primer paso,\n"
"el olor acre te produce náuseas.\n"
"\n"
"¡Muerte y cadáveres de demonios por todas partes!\n"
"\n"
"Ninguna pesadilla podría haberte\n"
"preparado para esta realidad.\n"
"\n"
"Te das cuenta de que este lugar\n"
"no estaba destinado para\n"
"los vivos.\n";

INTER05_TXT = "¡Felicidades!\n"
"Has encontrado...\n"
"\n"
"HÉCTICO\n"
"\n"
"Solo los mejores cosecharán\n"
"sus recompensas.\n";

INTER06_TXT = "Por fin...\n"
"¡La madre de las bestias ha sido aniquilada!\n"
"Por primera vez, los demonios conocen lo que es el miedo.\n"
"Mientras la sangre y el sudor caen de tu casco,\n"
"presencias el puro terror de los demonios al escapar.\n"
"\n"
"Querías tener tus vacaciones y tu terapia,\n"
"pero desafortunadamente, tu victoria es efímera.\n"
"\n"
"La base y el portal están destruidos. ¡No hay vuelta atrás!\n"
"\n"
"Mientras la locura y la sed de sangre consumen tu mente,\n"
"piensas que es mejor dejar que la UAC crea que has muerto.\n"
"\n"
"Sabiendo que el Infierno no puede ser destruido,\n"
"decides permanecer en el Infierno.\n"
"Continúas tu matanza sin fin para asegurarte de que\n"
"Doom no regrese, mientras el infierno teme tu nombre...\n";

INTER07_TXT = "Has decidido aventurarte hacia lo desconocido\n"
"antes de enfrentarte a la amenaza que acecha en el corazón del Infierno.\n"
"\n"
"Tras llegar a una extraña dimensión, te das cuenta de que\n"
"\n"
"un viejo amigo quiere tenerte para la cena.\n"
"\n"
"¡Que empiece el entretenimiento!\n";

INTER08_TXT = "Por fin has llegado a la guarida de la madre de los demonios.\n"
"\n"
"Tras luchar a través del infierno, la madre de los demonios está ante ti.\n"
"\n"
"Ve y preséntale tus respetos.\n"
"\n"
"Ella te está esperando...\n";

//Reckoning Episode Intermissions

RECMID_TXT = "De pie entre los restos en descomposición\n"
"del guardián del portal y sus sirvientes, te\n"
"burlas de los débiles esfuerzos del infierno para evitar\n"
"que entres en su mundo natal.\n"
"A continuación yace la única puerta restante hacia el\n"
"miserable dominio de los demonios, y tu única oportunidad\n"
"de poner fin a esta pesadilla\n"
"de una vez por todas...\n";

RECEND_TXT = "El grito agonizante del ser más poderoso\n"
"del infierno destroza tus sentidos y resuena\n"
"a través de las incontables millas de la superficie del infierno.\n"
"Un extraño portal se revela, y al cruzarlo,\n"
"exhalas un profundo suspiro de\n"
"alivio. Al fin, los terrores demoníacos que\n"
"invadieron tu mundo han sido aplastados\n"
"por tu mano poderosa, y si alguna vez vuelven a levantarse,\n"
"siempre te temerán a ti y al\n"
"juicio final que descargaste sobre ellos...\n";

//////////////////////////////////////////////////////////////////
// Tags for bots

TAGBD_BOT1 = "Recluta";
TAGBD_BOT2 = "Destructor";
TAGBD_BOT3 = "Ejecutor";
TAGBD_BOT4 = "Belicista";

BOT1_INTRO_TXT1 = "¡Bienvenido al paraíso!";
BOT1_INTRO_TXT2 = "Que empiece la fiesta.";
BOT1_INTRO_TXT3 = "Bueno, ¡hora de divertirse!";
BOT1_INTRO_TXT4 = "Genial, ¡otra vez este agujero de mierda!";
BOT1_INTRO_TXT5 = "¿Cuánto tiempo más tendremos que luchar en estos pozos de mierda?";
BOT1_INTRO_TXT6 = "¡Los voy a matar a todos!";
BOT1_INTRO_TXT7 = "¡A dar caña!";
BOT1_INTRO_TXT8 = "¡Voy a por ti!";
BOT1_INTRO_TXT9 = "Espera ahí. Llegaré pronto.";
BOT1_INTRO_TXT10 = "Voy a disfrutar esto.";
BOT1_INTRO_TXT11 = "¡Hora de romper unos cuantos dientes!";
BOT1_INTRO_TXT12 = "¡Ustedes, idiotas, no tienen ni una sola oportunidad!";

BOT1_FRAG_TXT1 = "¡Quédate en el suelo, joder!";
BOT1_FRAG_TXT2 = "¡Quédate muerto esta vez!";
BOT1_FRAG_TXT3 = "¡No te levantes por mi culpa!";
BOT1_FRAG_TXT4 = "¡Sorpresa! ¡Estás muerto!";
BOT1_FRAG_TXT5 = "¡Tan codicioso como un cerdo!";
BOT1_FRAG_TXT6 = "¿Cómo van las cosas por ahí abajo?";
BOT1_FRAG_TXT7 = "Descansa en pedazos.";
BOT1_FRAG_TXT8 = "¿Dormido en el trabajo?";
BOT1_FRAG_TXT9 = "¡Genial!";
BOT1_FRAG_TXT10 = "Levántate, vago de mierda. ¡Solo es una herida leve!";
BOT1_FRAG_TXT11 = "Por un momento, tus dulces gritos de agonía hicieron callar las voces.";
BOT1_FRAG_TXT12 = "Te recuerdo en Phobos. Saliste huyendo. Pero ahora te he encontrado.";

BOT1_KILLED_TXT1 = "¡Maldito con suerte!";
BOT1_KILLED_TXT2 = "¡Vas a pagar muy caro por eso!";
BOT1_KILLED_TXT3 = "¡Enano de mierda!";
BOT1_KILLED_TXT4 = "¡¿De dónde coño has salido?!";
BOT1_KILLED_TXT5 = "¡Esto apesta a mierda!";

BOT1_ROAMING_TXT1 = "¿Dónde coño estás?";
BOT1_ROAMING_TXT2 = "¡Retrocede o vete a la mierda!";
BOT1_ROAMING_TXT3 = "¡No podrás esconderte de mí para siempre!";
BOT1_ROAMING_TXT4 = "¡Vamos a decorar un poco!";
BOT1_ROAMING_TXT5 = "¡Sal, sal, estés donde estés!";

BOT1_NOROAMING_TXT1 = "¡Ustedes, cabrones, no me van a parar!";
BOT1_NOROAMING_TXT2 = "¡Aún no hemos terminado!";
BOT1_NOROAMING_TXT3 = "¡Espera! ¡Aún no hemos terminado!";
BOT1_NOROAMING_TXT4 = "¡Dame una oportunidad, joder!";
BOT1_NOROAMING_TXT5 = "¡Esto se está volviendo una mierda!";

BOT1_ENRAGED_TXT1 = "¡VETE A LA MIERDA, IMBÉCIL!";
BOT1_ENRAGED_TXT2 = "¡¡ESTÁS PIDIENDO A GRITOS QUE TE TORTURE!!";
BOT1_ENRAGED_TXT3 = "¡TE VOY A DESTROZAR!";
BOT1_ENRAGED_TXT4 = "¡LÁRGATE DE AQUÍ!";
BOT1_ENRAGED_TXT5 = "¡TE HARÉ PAGAR!";

BOT1_DEMORALIZED_TXT1 = "Ojalá todo este espectáculo de mierda se detuviera.";
BOT1_DEMORALIZED_TXT2 = "Me voy a echar una siesta. Despiértame después.";
BOT1_DEMORALIZED_TXT3 = "¡Siempre me terminan jodiendo!";
BOT1_DEMORALIZED_TXT4 = "¡Ya no puedo aguantar más esta basura!";
BOT1_DEMORALIZED_TXT5 = "¡Más me vale rendirme!";

BOT1_WIN_TXT1 = "¡Me encanta pintar el mapa con sangre y tripas!";
BOT1_WIN_TXT2 = "Bueno, ¡eso salió bastante bien!";
BOT1_WIN_TXT3 = "¡He disfrutado eso!";
BOT1_WIN_TXT4 = "Mi trabajo aquí ha terminado. Hora de seguir adelante...";
BOT1_WIN_TXT5 = "Todos los caminos te llevan directamente al infierno.";

BOT1_LOSE_TXT1 = "La próxima vez será mejor que tengas cuidado.";
BOT1_LOSE_TXT2 = "Me alegro de que esto haya terminado.";
BOT1_LOSE_TXT3 = "¡Menuda cantidad de mierda!";
BOT1_LOSE_TXT4 = "¡Creo que he tenido suficiente por hoy!";
BOT1_LOSE_TXT5 = "¡No tendrás tanta suerte la próxima vez!";
BOT1_LOSE_TXT6 = "¡Date una palmadita en la espalda!";
BOT1_LOSE_TXT7 = "¡Maldito con suerte!";
BOT1_LOSE_TXT8 = "Esto no es el final. ¡Volveré para terminar con esto!";

//BD64 MAP OPTIONS
FO_OPTION_MAP_OP = "Opciones de mapas";
FO_OPTION_MAP_OP_TXT = "(Estas opciones SOLO funcionan con los mapas de BD64)";
FO_OPTION_MAP_EASY = "Jugar mapas Map08 y Map28 más fáciles (sin jefe final extendido) =";
FO_OPTION_MAP_TC = "Añadir mapas de Absolution TC a la campaña =";
FO_OPTION_MAP_TITLE = "Mostrar secuencia del título de apertura original de Doom 64 al iniciar";
FO_OPTION_MAP_TITLE_TXT = "Mostrar mapa del título de apertura (requiere reinicio) =";
FO_MENU_MAP_EFX = "Efectos del mapa";
FO_OPTION_EFX_RAIN = "Activar efecto de lluvia =";